apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: test-chatbot-2026030501
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tpetkos/test-chatbot-2026030501:52a8d9605e193aaa7ccc7102df9f0077ed028e22@sha256:993f92acbb3c721a69cf99fa434340cc0121ad4272ca3b1a6ef40f811619b3c9 # use pre-built to bootstrap
          name: app-inference
